module.exports={
    CHECKEMAIL : "CHECKEMAIL",
    SIGNUP : "SIGNUP",
    LOGIN : "LOGIN",
    LOGOUT : "LOGOUT",
    SAVEPROFILE : "SAVEPROFILE",
    FETCHEVENTS : "FETCHEVENTS", 
    FETCHEVENTSBYTECH: "FETCHEVENTSBYTECH",
    FETCHEVENTSBYCAT: "FETCHEVENTSBYCAT"
  };
  